site_name: Cipher BT
site_url: https://cipher.nanvel.com
use_directory_urls: false
repo_url: https://github.com/nanvel/cipher-bt
nav:
    - Home: index.md
    - "Getting started": getting-started/index.md
    - "Install locally": getting-started/install-locally.md
    - Concepts: concepts.md
theme:
    name: readthedocs
    hljs_languages:
        - yaml
        - json
        - csv
        - python
