site_name: Cipher BT
site_url: https://cipher.nanvel.com
use_directory_urls: false
repo_url: https://github.com/nanvel/cipher-bt
nav:
    - Home: index.md
    - Installation: installation.md
    - Components: components.md
    - FAQ: faq.md
    - Examples: examples/index.md
theme:
    name: readthedocs
    hljs_languages:
        - yaml
        - json
        - csv
        - python
