site_name: Cipher BT
site_url: https://cipher.nanvel.com
use_directory_urls: false
repo_url: https://github.com/nanvel/cipher-bt
nav:
    - Introduction: index.md
    - Installation: installation.md
    - Tutorial: tutorial.md
    - Components: components.md
    - FAQ: faq.md
    - Examples:
        - examples/cmc.md
        - examples/vumanchu_cipher_b.md
theme:
    name: material
    features:
        - navigation.sections
        - navigation.instant
    palette:
        primary: teal
    font:
        text: Roboto
markdown_extensions:
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.highlight:
          use_pygments: true
    - meta
    - admonition
