name: publish-docs

on:
  push:
    branches:
      - master

jobs:
  publish-docs:
    name: Publish docs to cipher.nanvel.com

    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install "mkdocs>=1.4.2,<2"
      - run: pip install "mkdocs-material>=9.0.7,<10"
      - run: mkdocs build

      - name: Publish
        uses: reggionick/s3-deploy@v3
        with:
          folder: site
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.AWS_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: '/*'
          delete-removed: true
          no-cache: false
          private: true
