name: run-tests

on:
  push:
    branches:
      - master

jobs:
  publish-docs:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - uses: astral-sh/setup-uv@v5

      - run: uv sync --locked --dev

      - run: uv run pytest tests
